services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/php:8.4
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - 9090:8080
